version: '3.8'

services:


  frontend:
    build: ./frontend
    container_name: flask-frontend
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - BACKEND_URL=http://ec2-43-205-178-23.ap-south-1.compute.amazonaws.com:5000
    volumes:
      - ./frontend:/app
    networks:
      - flask-network
  

networks:
  flask-network:
    driver: bridge

volumes:
  frontend_data:
